[Service]
# The ExecStartPost script modifies the permissions of cgroup subgroups under the custom slice
ExecStartPost=/usr/local/bin/cgroup.sh
Slice=rstudioconnect.slice
Delegate=yes
DelegateSubgroup=connect